---
- name: Create a Jenkins namespace
  community.kubernetes.k8s:
    name: jenkins
    api_version: v1
    kind: Namespace
    state: present

- name: Add stable chart repo
  community.kubernetes.helm_repository:
    name: jenkinsci
    repo_url: "https://charts.jenkins.io"

- name: Read Jenkins persistent volume
  community.kubernetes.k8s:
    state: present
    namespace: jenkins
    template: 'jenkins-volume.yml.j2'

- name: Read service account template
  community.kubernetes.k8s:
    state: present
    namespace: jenkins
    template: 'jenkins-sa.yml.j2'

- name: Template a file to /opt/helm/jenkins-values.yml
  become: true
  copy:
    src: jenkins-values.yml
    dest: /opt/helm/jenkins-values.yml
    mode: '0644'

- name: Helm Install jenkins
  community.kubernetes.helm:
    name: jenkins
    chart_ref: jenkinsci/jenkins
    release_namespace: jenkins
    values_files:
      - /opt/helm/jenkins-values.yml
